### ISSUE TITLE
Whitespaces will not be deleted

### ISSUE THREAD

**Issue by julkue** [boushley/metalsmith-beautify#2]
I know this is not a bug of this plugin, as it simply uses js-beautify. However, what I expect from such a plugin is that it completely beautifies HTML. When having if or each conditions (like when using handlebars), whitspaces will not be removed. Maybe you can fix this on top?

**Comment by boushley** [comment]
I'm not doing much active development on this project at this time.

If you wanted to take a stab at a PR though I'd definitely be interested in how you pull that off.

**Comment by julkue** [comment]
Thanks for merging. Finally, could you please publish a new version on npm?

**Comment by boushley** [comment]
Done and done.
